analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    prefer_const_constructors: ignore
    unused_element: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml
